
package yodawsdl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "http://www.yodaspeak.co.uk/webservice/yodatalk", targetNamespace = "urn:http://www.yodaspeak.co.uk/webservice/yodatalk", wsdlLocation = "http://yodaspeak.co.uk/webservice/yodatalk.php?wsdl")
public class YodaService
    extends Service
{

    private final static URL HTTP_002F_002FWWWYODASPEAKCOUK_002FWEBSERVICE_002FYODATALK_WSDL_LOCATION;
    private final static WebServiceException HTTP_002F_002FWWWYODASPEAKCOUK_002FWEBSERVICE_002FYODATALK_EXCEPTION;
    private final static QName HTTP_002F_002FWWWYODASPEAKCOUK_002FWEBSERVICE_002FYODATALK_QNAME = new QName("urn:http://www.yodaspeak.co.uk/webservice/yodatalk", "http://www.yodaspeak.co.uk/webservice/yodatalk");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://yodaspeak.co.uk/webservice/yodatalk.php?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        HTTP_002F_002FWWWYODASPEAKCOUK_002FWEBSERVICE_002FYODATALK_WSDL_LOCATION = url;
        HTTP_002F_002FWWWYODASPEAKCOUK_002FWEBSERVICE_002FYODATALK_EXCEPTION = e;
    }

    public YodaService() {
        super(__getWsdlLocation(), HTTP_002F_002FWWWYODASPEAKCOUK_002FWEBSERVICE_002FYODATALK_QNAME);
    }

    public YodaService(WebServiceFeature... features) {
        super(__getWsdlLocation(), HTTP_002F_002FWWWYODASPEAKCOUK_002FWEBSERVICE_002FYODATALK_QNAME, features);
    }

    public YodaService(URL wsdlLocation) {
        super(wsdlLocation, HTTP_002F_002FWWWYODASPEAKCOUK_002FWEBSERVICE_002FYODATALK_QNAME);
    }

    public YodaService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, HTTP_002F_002FWWWYODASPEAKCOUK_002FWEBSERVICE_002FYODATALK_QNAME, features);
    }

    public YodaService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public YodaService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Http_002f_002fWwwYodaspeakCoUk_002fWebservice_002fYodatalkPortType
     */
    @WebEndpoint(name = "http://www.yodaspeak.co.uk/webservice/yodatalkPort")
    public YodatalkPortType getYodatalkPort() {
        return super.getPort(new QName("urn:http://www.yodaspeak.co.uk/webservice/yodatalk", "http://www.yodaspeak.co.uk/webservice/yodatalkPort"), YodatalkPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Http_002f_002fWwwYodaspeakCoUk_002fWebservice_002fYodatalkPortType
     */
    @WebEndpoint(name = "http://www.yodaspeak.co.uk/webservice/yodatalkPort")
    public YodatalkPortType getYodatalkPort(WebServiceFeature... features) {
        return super.getPort(new QName("urn:http://www.yodaspeak.co.uk/webservice/yodatalk", "http://www.yodaspeak.co.uk/webservice/yodatalkPort"), YodatalkPortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (HTTP_002F_002FWWWYODASPEAKCOUK_002FWEBSERVICE_002FYODATALK_EXCEPTION!= null) {
            throw HTTP_002F_002FWWWYODASPEAKCOUK_002FWEBSERVICE_002FYODATALK_EXCEPTION;
        }
        return HTTP_002F_002FWWWYODASPEAKCOUK_002FWEBSERVICE_002FYODATALK_WSDL_LOCATION;
    }

}
